#!/bin/bash

CMD="$(pamixer --get-default-sink)"
HEADPHONES="alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo"
SPEAKERS="alsa_output.pci-0000_2b_00.1.hdmi-stereo-extra1"
VOL="$(pamixer --get-volume-human)"

if [[ $CMD =~ $HEADPHONES ]]; then
    echo -e " $VOL"
elif [[ $CMD =~ $SPEAKERS ]]; then
    echo -e "蓼 $VOL"
else
    echo ""
fi
