#!/bin/bash

function powermenu {
    OPTIONS="Cancel\nShutdown\nRestart\nLock\nLogout"
    SELECTED=$(echo -e $OPTIONS | dmenu)

    if [[ $SELECTED = "Shutdown" ]]; then
        poweroff
    elif [[ $SELECTED = "Restart" ]]; then
        reboot
    elif [[ $SELECTED = "Lock" ]]; then
        slock
    elif [[ $SELECTED = "Logout" ]]; then
        killall -p dwm
    elif [[ $SELECTED = "Cancel" ]]; then
        return
    fi
}

powermenu
