#!/bin/bash

function powermenu {
    OPTIONS="Cancel\nShutdown\nRestart\nSleep\nLock"
    SELECTED=$(echo -e $OPTIONS | dmenu)

    if [[ $SELECTED = "Shutdown" ]]; then
        poweroff
    elif [[ $SELECTED = "Restart" ]]; then
        reboot
    elif [[ $SELECTED = "Sleep" ]]; then
        systemctl suspend
    elif [[ $SELECTED = "Lock" ]]; then
        slock
    elif [[ $SELECTED = "Cancel" ]]; then
        return
    fi
}

powermenu
